language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
branches:
  only:
    master
before_install:
  - travis_retry composer self-update
  - composer install
script: phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests
